# Generated by Django 4.1.7 on 2023-05-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("body", "0002_userprofile_alter_comment_user_alter_post_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="date_of_registration",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="login",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password",
        ),
        migrations.AlterField(
            model_name="comment",
            name="post_added_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_added_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
