# Generated by Django 4.1.7 on 2023-05-26 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("body", "0003_remove_userprofile_date_of_registration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
    ]
