# Generated by Django 4.1.7 on 2023-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("body", "0004_remove_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
