# Generated by Django 4.2.1 on 2023-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_post_image_alter_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
