# Generated by Django 4.2.1 on 2023-06-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0007_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
