# Generated by Django 4.2.1 on 2023-06-11 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0009_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_added_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
