# Generated by Django 4.2.1 on 2023-06-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0013_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
