# Generated by Django 4.2.1 on 2023-06-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0015_alter_comment_content_alter_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='post',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
