# Generated by Django 4.2.1 on 2023-06-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0016_remove_password_post_delete_image_delete_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
